//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stories.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stories.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SyntaxDefinition name=&quot;ADAQ&quot;
        ///                  xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///
        ///    &lt;!-- This is the main ruleset. --&gt;
        ///    &lt;RuleSet&gt;
        ///
        ///
        ///      &lt;Keywords fontWeight=&quot;bold&quot; foreground=&quot;Blue&quot;&gt;
        ///
        ///        &lt;Word&gt;executable&lt;/Word&gt;
        ///        &lt;Word&gt;from&lt;/Word&gt;
        ///        &lt;Word&gt;accessible&lt;/Word&gt;
        ///                &lt;Word&gt;in&lt;/Word&gt;
        ///                  &lt;Word&gt;necessary&lt;/Word&gt;
        ///                  &lt;Word&gt;possibly&lt;/Word&gt;
        ///      
        ///      
        ///      
        ///      
        ///      
        ///    &lt;/Keywords&gt;
        ///      &lt;Keywo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdaQSyntaxt {
            get {
                return ResourceManager.GetString("AdaQSyntaxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SyntaxDefinition name=&quot;ADA&quot;
        ///                  xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///
        ///    &lt;!-- This is the main ruleset. --&gt;
        ///    &lt;RuleSet&gt;
        ///
        ///
        ///      &lt;Keywords fontWeight=&quot;bold&quot; foreground=&quot;Blue&quot;&gt;
        ///        &lt;Word&gt;initially&lt;/Word&gt;
        ///        &lt;Word&gt;always&lt;/Word&gt;
        ///        &lt;Word&gt;observable&lt;/Word&gt;
        ///        &lt;Word&gt;releases&lt;/Word&gt;
        ///        &lt;Word&gt;noninertial&lt;/Word&gt;
        ///        &lt;Word&gt;after&lt;/Word&gt;
        ///        &lt;Word&gt;when&lt;/Word&gt;
        ///        &lt;Word&gt;causes&lt;/Word&gt;
        ///        &lt;Word&gt;impossible&lt;/Word&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdaSyntaxt {
            get {
                return ResourceManager.GetString("AdaSyntaxt", resourceCulture);
            }
        }
    }
}
